name: Tests
on: push

jobs:
  # <---------------- TEST BASIC CONFIG ------------------>
  basic:
    name: Basic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Basic Test
        uses: ./
        with:
         image: alpine:latest
         accept-extensions: pem

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Basic Report
          path: dockle-report.json

  # <--------------- TEST ADVANCED CONFIG ---------------->
  advanced:
    name: Advanced
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Advanced Test
        uses: ./
        with:
          image: alpine:latest
          report-format: sarif
          report-name: dockle
          failure-threshold: fatal
          exit-code: 1
          dockle-version: 0.4.5
          accept-extensions: pem

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: dockle.sarif
          wait-for-processing: false
